national_team_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstenationalmannschaften/marktwertetop"

wr_club_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstemannschaften/marktwertetop"
tr_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=174&kontinent_id=0&yt0=G%C3%B6ster"
eng_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=189&kontinent_id=0&yt0=G%C3%B6ster"
ita_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=75&kontinent_id=0&yt0=G%C3%B6ster"
esp_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=157&kontinent_id=0&yt0=G%C3%B6ster"
fra_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=50&kontinent_id=0&yt0=G%C3%B6ster"
ger_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=40&kontinent_id=0&yt0=G%C3%B6ster"
bel_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=19&kontinent_id=0&yt0=G%C3%B6ster"
net_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=122&kontinent_id=0&yt0=G%C3%B6ster"
por_club_val = "https://www.transfermarkt.com.tr/vereins-statistik/wertvollstemannschaften/marktwertetop/plus/0/galerie/0?land_id=136&kontinent_id=0&yt0=G%C3%B6ster"

wr_footballer_all_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop"
wr_gkp_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Torwart&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=0&kontinent_id=0&yt0=G%C3%B6ster"
wr_def_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Abwehr&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=0&kontinent_id=0&yt0=G%C3%B6ster"
wr_mid_val ="https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Mittelfeld&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=0&kontinent_id=0&yt0=G%C3%B6ster"
wr_frwd_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Sturm&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=0&kontinent_id=0&yt0=G%C3%B6ster"

tr_footballer_all_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=alle&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=174&kontinent_id=0&yt0=G%C3%B6ster"
tr_gkp_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Torwart&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=174&kontinent_id=0&yt0=G%C3%B6ster"
tr_def_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Abwehr&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=174&kontinent_id=0&yt0=G%C3%B6ster"
tr_mid_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Mittelfeld&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=174&kontinent_id=0&yt0=G%C3%B6ster"
tr_frwd_val = "https://www.transfermarkt.com.tr/spieler-statistik/wertvollstespieler/marktwertetop/plus/0/galerie/0?ausrichtung=Sturm&spielerposition_id=alle&altersklasse=alle&jahrgang=0&land_id=174&kontinent_id=0&yt0=G%C3%B6ster"


champions = "https://www.transfermarkt.com.tr/uefa-champions-league/marktwerte/pokalwettbewerb/CL"
europa = "https://www.transfermarkt.com.tr/europa-league/marktwerte/pokalwettbewerb/EL"
superlig = "https://www.transfermarkt.com.tr/super-lig/marktwerte/wettbewerb/TR1"
premier = "https://www.transfermarkt.com.tr/premier-league/marktwerte/wettbewerb/GB1"
bundesliga = "https://www.transfermarkt.com.tr/1-bundesliga/marktwerte/wettbewerb/L1"
ligue1 = "https://www.transfermarkt.com.tr/ligue-1/marktwerte/wettbewerb/FR1"
laliga = "https://www.transfermarkt.com.tr/primera-division/marktwerte/wettbewerb/ES1"
seria = "https://www.transfermarkt.com.tr/serie-a/marktwerte/wettbewerb/IT1"